// components/TypeBox.tsx
import React from "react";
import { typeInfo } from "@/lib/typeinfo";

interface TypeBoxProps {
  type_id: number;
}

export default function TypeBox({ type_id }: TypeBoxProps) {
  const info = typeInfo[type_id];
  const { name, type_color } = info ?? {
    name: "",
    type_color: "",
  };
  return (
    <div
      className={`flex justify-center items-center rounded-sm w-5/12 ${type_color}`}
    >
      <p className={`text-stroke text-xxs px-1 py-0 by-0 text-white outline-1`}>
        {name}
      </p>
    </div>
  );
}

// src/app/shared/components/type-box/type-box.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-type-box',
  templateUrl: './type-box.component.html',
})
export class TypeBoxComponent {
  @Input() type: any = {} as any;
}

<div
  class="flex justify-center items-center rounded"
  data-testid="type-box"
  [ngClass]="{
    'py-1 px-2 w-20 text-xs': size === 'sm',
    'py-2 px-4 w-24 text-sm': size === 'md',
    'py-3 px-6 w-28 text-md': size === 'lg'
  }"
  [style.background]="'#' + type.type_color"
>
  <span class="font-bold white-outlined" data-testid="type-box-text">{{
    type.name
  }}</span>
</div>
